site_name: 从0动手做Python Web框架
site_url: https://renshou753.github.io/wsgi_web
nav:
  - 介绍: intro.md
  - Python Web框架: python_web.md
  - Hello WSGI: hello.md
  - WSGI中间件: middleware.md
  - 路由: route.md
  - Reference: reference.md
theme: readthedocs
